FROM node:22-alpine

RUN corepack enable && corepack prepare pnpm@latest --activate

RUN pnpm --version

WORKDIR /server

COPY package.json pnpm-lock.yaml ./

RUN pnpm install

COPY . .

RUN pnpm run build

EXPOSE 8000

CMD [ "pnpm", "start" ]
